### ISSUE TITLE
Bubble correction

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimaCore.jl#1019]
## Purpose
The purpose of this SDI is to describe the development plan to add the bubble correction feature. To the best of my current knowledge this feature request is not well documented, so this SDI draft will probably be modified as I learn more about the specs and problem statement. 

## Cost/benefits/risks
Benefits: Bubble correction is supposed to improve the numerical surface area computation of any given (discrete) mesh. A more accurate surface area, in turn, will improve the accuracy of surface fluxes calculation. For low-order geometries (like the one we use) the numerical area of the domain (and of an element) is given by the sum of integration weights. But because of the low-order discretization, the numerical area is not equal to the geometric area. The "epsilon bubble correction" is supposed to fix this discrepancy by modifying the inner weights in each element so that geometric and numerical areas of each element match. 

Risks: there is not sufficient documentation that we could find on the topic, so it is possible that we might have a naive conceptual map and are not fully able to list the details or challenges of the implementation. 

## Producers
@valeriabarra with potential collaborators and reviewers: @simonbyrne and @charleskawczynski 

## Components
Implement the bubble correction algorithm and related tests. Initially, we may want to "augment" the Jacobian so that we keep both the corrected and non-corrected versions for testing/debugging/comparison purposes. 

- First we need to compute the geometric face area to know how far off the numerical one is. TempestRemap has a reference [implementation](https://github.com/ClimateGlobalChange/tempestremap/blob/b622790cc993998dff93e038af38d17b786c98b7/src/GridElements.cpp#L129). Not sure at the moment how many other utilities from the +3K LOC in [GridElements.cpp](https://github.com/ClimateGlobalChange/tempestremap/blob/master/src/GridElements.cpp) are going to be needed as well.

## Inputs
Implementation references in other projects: 

-  [HOMME](https://github.com/E3SM-Project/E3SM/blob/19b51f71af7dc39ba6bb344a8543f7dd5203644d/components/homme/src/share/geometry_mod.F90#L79) 
- [TempestRemap](https://github.com/ClimateGlobalChange/tempestremap/blob/master/src/FiniteElementTools.cpp#L376) 

## Results and deliverables
A description of the key results, deliverables, quality expectations, and performance metrics.

## Task breakdown
A preliminary list of PRs and a preliminary timeline of PRs, milestones, and key results.
- [ ] Task 1: Implement a calculation of an element's face geometric area. 
    - [ ] This involves checking if the faces are convex or concave and triangulate the surface for an accurate area calculation for non planar elements
- [ ] Task 2: "Augment" or correct weights of interior points so that the difference between the numeric area and geometric area is minimized. 
- [ ] Task 3: use existing sphere space [unit tests](https://github.com/CliMA/ClimaCore.jl/blob/6918baf42f656cca70b81224be6662d0375194d3/test/Spaces/sphere.jl#L18) to check that we reach a more accurate surface area with fewer mesh refinement than currently necessary. 
...

## Reviewers
@simonbyrne and @charleskawczynski

**Comment by valeriabarra** [comment]
The first thing I would do is to add an optional boolean flag to the `SpectralElementSpace2D` [constructor](https://github.com/CliMA/ClimaCore.jl/blob/6918baf42f656cca70b81224be6662d0375194d3/src/Spaces/spectralelement.jl#L170), say, `enable_bubble` (initially `false` by default), to apply the bubble correction to the Jacobain `J` and Jacobian*weights `WJ` entries of the `LocalGeometry`, but still keep these field names the same. 
The other idea could have been to use an ad-hoc constructor for `SpectralElementSpace2D`, say `SpectralElementBubbleSpace2D` but this would have caused too much code duplication.

**Comment by simonbyrne** [comment]
Can you write up what you understand https://github.com/ClimateGlobalChange/tempestremap/blob/master/src/FiniteElementTools.cpp#L376-L423 to be doing? (separate from the area computation)

**Comment by valeriabarra** [comment]
I have typed up the notes here
[CliMA_Bubble_Correction_Notes.pdf](https://github.com/CliMA/ClimaCore.jl/files/10116296/CliMA_Bubble_Correction_Notes.pdf)

**Comment by simonbyrne** [comment]
I don't think 1.1.1 is quite correct: [`dataGLLJacobian[j][i][k]`](https://github.com/ClimateGlobalChange/tempestremap/blob/ddee889eacf4635c19abb3468bdc5d884e2c190c/src/FiniteElementTools.cpp#L358-L372) is equivalent to our $W_{i,j} J_{i,j}$, and so

Define

$$  \Delta A = A_{\text{exact}} - \sum_{i,j} W_{i,j} J_{i,j} $$

In the linear case (`Nq = 2`) the "adjusted" Jacobian  $\hat J_{i,j}$ then should be defined such that

$$ W_{i,j} \hat J_{i,j} = W_{i,j} J_{i,j} + W_{i,j} \Delta A $$ 

or simply

$$ \hat J_{i,j} = J_{i,j} + \Delta A .$$ 

In the higher-order case (`Nq > 2`), define

$$ \mathring A = \sum_{i,j \ \text{interior}} W_{i,j} J_{i,j} $$

Then $\hat J_{i,j}$ is defined such that

$$ W_{i,j} \hat J_{i,j} = W_{i,j} J_{i,j} \frac{\mathring A + \Delta A}{\mathring A} \quad i,j \ \text{interior} $$ 

or simply

$$ \hat J_{i,j} = J_{i,j} \frac{\mathring A + \Delta A}{\mathring A} \quad i,j \ \text{interior} $$

**Comment by valeriabarra** [comment]
Thank you! I updated my notes, just for clarity/correctness sake 
[CliMA_Bubble_Correction_Notes (2).pdf](https://github.com/CliMA/ClimaCore.jl/files/10118081/CliMA_Bubble_Correction_Notes.2.pdf)

**Comment by valeriabarra** [comment]
I know this has been closed as completed, but I am investigating some conservation issues with the bubble correction now. We said that `dataGLLJacobian` in Paul (@paullric)'s [code](https://github.com/ClimateGlobalChange/tempestremap/blob/master/src/FiniteElementTools.cpp#L376) was our `WJ`, but at this point I am second-guessing if this interpretation was correct
