### ISSUE TITLE
GPU performance improvements

### ISSUE THREAD

**Issue by sriharshakandala** [CliMA/ClimaCore.jl#1428]
## Purpose
Achieve a computational throughput of >8 SYPD (simulated years per day) on 4 (A100) GPUs for the dynamical core at 100 km horizontal resolution, with strong scaling efficiency exceeding 85% when using 16 GPUs.

Link to any relevant PRs/issues.

## Cost/benefits/risks
An analysis of the cost/benefits/risks associated with the proposal.

## Producers
A list of the resources and named personnel required to implement the Proposal.

## Components
A description of the main components of the software solution.

## Inputs
A description of the inputs to the solution (designs, references, equations, closures, discussions etc).

## Results and deliverables
A description of the key results, deliverables, quality expectations, and performance metrics.

## Task breakdown
A preliminary list of PRs and a preliminary timeline of PRs, milestones, and key results.
- [ ] Horizontal kernel improvements
  - [ ] Better use of threading
  - [ ] Implement reference kernels, use  them for tuning
  - [ ] QA examples (e.g. Hyperdiffusion)
- [ ] Vertical
  - [ ] Better use of threading [[PR#1398](https://github.com/CliMA/ClimaCore.jl/pull/1398)]
  - [ ] QA examples (e.g. flux divergence, jacobian operation)
  - [ ] Jacobian formulation
- [ ] Timestepping
  - [ ] Identify and fix timestepper bottlenecks

 
...

## Reviewers
The names of CliMA personnel who will review the Proposal and subsequent PRs.
