### ISSUE TITLE
Flux-corrected transport

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimaCore.jl#851]
## Purpose
Flux-corrected transport is a requested feature. 

My current understanding is that this, applied only in the vertical direction, is a combination of the first-order upwinding  ([UpwindBiasedProductC2F](https://clima.github.io/ClimaCore.jl/dev/operators/#ClimaCore.Operators.UpwindBiasedProductC2F)) and third-order upwinding ([Upwind3rdOrderBiasedProductC2F](https://clima.github.io/ClimaCore.jl/dev/operators/#ClimaCore.Operators.Upwind3rdOrderBiasedProductC2F)) schemes. 

Since this work builds on the third-order upwinding operator and there have been observed instabilities when using this operator in the high-resolution runs in ClimaAtmos, it is essential to first rule out any potential issue with the third-order upwinding operator first. 

There can be several options to combine these two low-and-high order operators. The simplest one is a linear combination of the two (I would call this the _vanilla case_), where one could reduce to first-order upwinding only, or third-order upwinding only, by switching on/off the correction factor coefficient. 

## Cost/benefits/risks
My understanding is that this flux-corrected transport will act similarly to the flux-limiters we currently have that act only in the horizontal direction, but in the vertical direction. Hence, the corrected flux will be ensured to be not large enough or small enough to generate new extrema in the vertically advected quantities.

## Producers
@valeriabarra with help of others if needed

## Components
This proposal shouldn't need to create/develop new operators, but should be able to reuse our existing operators (i.e., library code) and only combine them in application code, i.e., examples. 
Perhaps, when turning our attention to the non-vanilla applications, we may have to develop some fancy way of computing the correction factor and this might require new library code/utilities. 

## Inputs
Chapter 5.4 in the following reference: 
"Numerical Methods for Fluid Dynamics", by Dale Durran (2010)

## Results and deliverables
Use some of the existing examples and add the flux-corrected transport to show that some ripples/oscillations in the vertical direction can be reduced. Similarly to what was done in the limiters examples.

## Task breakdown
A preliminary list of PRs and a preliminary timeline of PRs, milestones, and key results.
- [x] Task 1: Start with the simple, vanilla case (Sec. 5.4 in reference book) Timeline less than a week.
     - [x] Task 1.1: Add spatial convergence unit tests for this case
     - [x] Task 1.2: Add temporal integration/unit test for this case
     - [x] Task 1.3: Add the vanilla case to a more complicated integration example: the deformation flow example.
- [ ] Task 2: Add more advanced cases from references (Expected timeline not so clear at the moment. Need to read more about the most advanced cases to assess their implementation challenges). Start with Sec. 5.4.1 in the reference book, i.e., "Boris and Book FCT" (1973):
     - [x] Task 2.1:  Edited: Add a new ClimaCore operator for the Boris and Book FCT
     - [x] Task 2.2: Add temporal integration/unit test for this case (<- this FCT type requires the usage of step-function specification, a la ClimaTimeSteppers, instead of tendency specification; so for now it is better to use it directly in temporal unit/integration tests). Reused part of the same unit test from Task 1.2, but adapted to use ClimaTimeSteppers.
     - [x] Task 2.3: Add the Boris and Book FCT case to a more complicated integration example: the deformation flow example.
- [ ] Task 3: Repeat with the next section, Sec. 5.4.2 in the reference book, i.e., "Zalesak corrector FCT" (1979):
     - [x] Task 3.1: Add a new ClimaCore operator for the Zalesak FCT (done by @Zhengyu-Huang  in #887 )
     - [x] Task 3.2: Add temporal integration/unit test for this case. (#887 reused the same one from Task 1.2)
     - [ ] Task 3.3: Add the Zalesak corrector FCT case to a more complicated integration example: the Hadley-like meridional circulation test case.
...

## Reviewers
@simonbyrne

**Comment by valeriabarra** [comment]
#852 takes care of Task 1

**Comment by valeriabarra** [comment]
For Task 2: I will use `examples/hybrid/sphere/limiters_deformation_flow.jl` example. This is a good candidate problem, since it uses the `ClimaTimeSteppers` step specification formulation and it has several `@test` we can check that we pass/fail

**Comment by valeriabarra** [comment]
The next level up FCT to try is the one from Sec. "5.4.1 Flux Correction: The Original Proposal" of the reference boook. 
If turns out to be not sufficient for the desired behavior we're hoping to get out of this FCT (i.e., the corrected flux maybe not be large enough or small enough to generate new extrema in the vertically advected quantities) then we can try to implement the one from the following section "5.4.2 The Zalesak Corrector" in the same reference book.

**Comment by Zhengyu-Huang** [comment]
Do we use flux correction for all the equations or only for the tracer equations?

**Comment by valeriabarra** [comment]
> Do we use flux correction for all the equations, including vertical velocity equation, or only for the tracer equations?

Only for the tracers, similar to the limiters in the horizontal

**Comment by Zhengyu-Huang** [comment]
> > Do we use flux correction for all the equations, including vertical velocity equation, or only for the tracer equations?
> 
> Only for the tracers, similar to the limiters in the horizontal

Do tracers include energy ? I agree that it is combination of first order upwind and third order upwind.  Have you started to implement it?  Should we focus mainly on Zalesak Corrector (5.4.2)  and Flux-Limiter Methods (5.5), I feel Flux-Limiter Methods is easier to implement

**Comment by valeriabarra** [comment]
In the example mentioned above (`deformation_flow.jl`) there is no energy. In other examples, where there is energy, we usually apply the third-order upwinding to enthalpy, e.g., 
```
@. Yₜ.c.ρe=-(ᶜdivᵥ(ᶠinterp(Y.c.ρ)*ᶠupwind_product(ᶠw,(ᶜρe+ᶜp)/Y.c.ρ)))
```
so I was imaging it being applied similarly, since it re-uses that operator. 

There was no mention so far of Sec 5.5., and I was told to start from the simplest and proceed incrementally, only in case it was not showing the desired behavior. So I started thinking about 5.4.1 and then, if not enough, proceed to 5.4.2 as mentioned above.

**Comment by Zhengyu-Huang** [comment]
Starting from 5.4.1 sounds good, the implementation is easier than 5.4.2. let me know when you start the draft PR.  I will double check whether we need to use it for energy, since I feel it is very difficulty to treat these flux correction implicitly with current implicit solver implementation.

**Comment by valeriabarra** [comment]
> I will double check whether we need to use it for energy, since I feel it is very difficulty to treat these flux correction implicitly with current implicit solver implementation.

But isn't that how we currently use it, regardless of FCT?

**Comment by Zhengyu-Huang** [comment]
> 

Yes, current we have Jacobian for first/third order upwinds, but if we add these corrections, like A matrix, it is not straightforward to implement Jacobian.
