### ISSUE TITLE
Reduce halo exchange communication during DSS

### ISSUE THREAD

**Issue by sriharshakandala** [CliMA/ClimaCore.jl#902]
## Purpose
The purpose of this SDI is to improve the design of the existing direct stiffness summation (DSS) code.

With the current design, all degrees-of-freedom for prognostic variables belonging to spectral elements on process neighbors are being communicated during DSS. For the 3D simulations, which are what we use for our production runs, the amount of data communicated is of the order `(N+1)^2 x Nv x N_neigh x N_prog`.

However, it is only required to communicate the degrees-of-freedom corresponding to the shared vertices and faces, which is lower at least by a factor of `N`. This would decrease the halo exchange communication costs during direct stiffness summation. Smaller messages also help hide communication with computation during DSS better.

## Benefits
Reduction in halo exchange communication during direct stiffness summation is expected to improve the overall scalability of the solver.

## Risks
Other factors, like the behavior of garbage collector in distributed simulations, could affect the scaling behavior of the solver and might need to be fixed to notice the full benefits of this PR. However, this is a step in the right direction and the tasks are independent.

## Producers
@sriharshakandala 

## Results and deliverables
Redesigned DSS code merged into main.
Performance and scaling data prior to and after the implementation of this PR.

### Task timeline
- [x] Build draft PR (09/27/2022)
- [x] Update existing DSS tests to cover new DSS algorithm (10/05/2022)
- [x] Preliminary performance evaluation (10/05/2022)
- [x] Preliminary documentation (10/05/2022)
- [x] Code review, performance evaluation/tuning (QA) (in progress)
- [x] Update documentation as needed
- [x] Merge PR

## Task breakdown
Build a perimeter iterator:
 - A perimeter iterator/array that iterates over the perimeter dof. 
 - The iterator is of length `nperimeter` and is identical for all spectral elements. 
 - For example, for a 2D distributed topology, this returns (i, j) for each of the (4) vertices and the (4) face dofs and will be of length `4 + 4 * (Nq-2)`.

Resizing the GhostBuffer:
 -  Resize the `GhostBuffer`  such that  send_data is a `1D` array of length `sum(send_lengths)` and recv_data is a `1D` array of length `sum(recv_lengths)`
```
struct GhostBuffer{G, D}
    graph_context::G
    send_data::D
    recv_data::D
end
```
 - Here `send_lengths` and `recv_lengths` contain the number of dof to be communicated to and from each of the `neighbor_pids` for a given process.

Build indexing array/iterator for loading send buffer:

 - An iterator/ragged array that stores the information needed for loading the send buffer. 
 - The iterator is of length `nperimeter x nsendelems` and provides at tuple of loading indices. 
 - There will be at most `1` index per `neighbor_pid`. 
 - This can alternatively be accomplished using a ragged array.

Evaluate revised workflow for weighted_dss!:

 - In the current weighted_dss code, the transform, untransform, weighting and dss operations are all fused. It is proposed to consider a revised work flow in the following order:
```
transform to physical space for horizontal vector components, multiply with weights (in-place, ghost dof)
perform local "ghost" DSS
initiate communication
transform to physical space for horizontal vector components, multiply with weights (in-place, local dof)
perform local DSS
untransform (in-place, local dof)
complete communication
ghost DSS
untransform (in-place, ghost dof)

```
Optimize/restructure current `transform/untransform` code:

 - Preliminary tests with DSS on 2D spectral element simulations indicate that the `transform/untransform` calls are using about 85% of total serial DSS time. These functions need to be optimized/restructured.

Note: The code will be initially developed to coexist with pre-existing DSS algorithm, until fully tested for accuracy and performance.

A preliminary list of PRs and a preliminary timeline of PRs, milestones, and key results.
- [x] #938
- [x] #955
- [x] #957
- [x] #969
- [x] #970
- [x] #971
- [x] Update documentation
- [x] #981
- [x] #980

## Reviewers
@simonbyrne

**Comment by bischtob** [comment]
@simonbyrne @sriharshakandala are we moving forward with this?

**Comment by tapios** [comment]
Can we add some rough timeline estimates (just to get an order of magnitude sense)?

**Comment by sriharshakandala** [comment]
It is approximately a couple of weeks of coding effort.
However, some items like `transform/untransform` effect many other functions in the code and the estimates for these are a bit complex!

**Comment by bischtob** [comment]
green light has been given on this task.

**Comment by sriharshakandala** [comment]
Since the implementation of this feature is completed in ClimaCore, can we close this issue? We can open new SDI's for additional optimization work! (@cmbengue, @simonbyrne  )

**Comment by bischtob** [comment]
If this is complete, let's close this @simonbyrne
