### ISSUE TITLE
Spectra for GCM configuration

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimaCore.jl#967]
## Purpose
Spectra on the sphere via spherical harmonics are a feature needed for diagnostic purposes. 

Link to any relevant PRs/issues: https://github.com/CliMA/ClimaDiagnostics/issues/1

Some of this diagnostic functionality existed in [`ClimateMachine`](https://github.com/CliMA/ClimateMachine.jl/tree/master/src/Common/Spectra) but will need to be ported over to ClimaCore and adapted to use its API/objects, and potentially optimized using existing Julia packages. 

## Cost/benefits/risks
Having spherical harmonics will allow us to calculate and plot the energy spectra to analyze turbulence or numerical dissipation (e.g., from hyperdiffusion). 

## Producers
Lead: @valeriabarra
Potential collaborators: @LenkaNovak , @akshaysridhar , @jiahe23 

## Components
On the sphere we want both 1D and 2D spectra. For these we need:
- Porting existing code:
  - [x] For 1D: Calculate the 1D (zonal) power spectra using the Fourier transform at each latitude and level from the 2D horizontal velocity field
  - [x] For 2D: Transform variable on lat-lon grid to the 2D spectral (spherical harmonic) space using `fft` on latitude circles (as for the 1D spectrum) and associated Legendre polynomials for meridians, and calculate spectra. 
- Enhancement
  - [ ] Reuse existing Julia libraries to favor library reuse to the extent possible, e.g., [`AssociatedLegendrePolynomials.jl`](https://github.com/jmert/AssociatedLegendrePolynomials.jl) for the calulation of the associated normalized Legendre polynomials and [`QuadGK.jl`](https://juliamath.github.io/QuadGK.jl/stable/) for Gaussian integration

## Inputs
References: 
- ClimateMachine [`Spectra`](https://github.com/CliMA/ClimateMachine.jl/tree/master/src/Common/Spectra) module and references therein:
    - Baer, ["An Alternate Scale Representation of Atmospheric Energy Spectra"](https://journals.ametsoc.org/view/journals/atsc/29/4/1520-0469_1972_029_0649_aasroa_2_0_co_2.xml), 1972
    - Ehrendorfer, ["Spectral Numerical Weather Prediction Models"](https://epubs.siam.org/doi/book/10.1137/1.9781611971996), 2011
     
## Results and deliverables

- [x] A ClimaCore subpackage that will live under `lib`, e.g., `lib/ClimaCoreSpectra`, which will include both library code under `src` and related tests under `test`, exercised through the usual `runtests.jl`. 
- [x] Unit test(s) 
  - [x] visual component for a specific spherical harmonic as the one in ClimateMachine did
  - [x] test against existing Python packages (e.g., https://shtools.github.io/SHTOOLS/complex-spherical-harmonics.html) (this was done in the original implementation)
  - [x] integration test / example that show the workflow: from a `Field` defined on the ClimaCore cubed-sphere to the regridding and specrta calculation  
- [x] Documentation in ClimaCore  

Integration in downstream repositories/packages:
- [ ] Implementation in ClimaCoupler diagnostics and visualization, featuring in the AMIP driver (I would open a separate issue for this in CCoupler for this)

## Task breakdown
A preliminary list of PRs and a preliminary timeline of PRs, milestones, and key results.
- [x] Development of the `lib/ClimaCoreSpectra` package [1 week?] 
- [x] unit testing
- [x] documentation
- [x] integration test/example that shows the full workflow (starting from a CC cubed-sphere, remapping to rll grid, and transforming to spectral space)

The four tasks above are implemented in https://github.com/CliMA/ClimaCore.jl/pull/979

Additional tasks for follow-up PRs: 
- [ ] Improved interface that uses ClimaCore `Fields` directly with internal calls to remapping infrastructure so to remove the burned from the user

Integration in downstream repositories/packages:
- [ ] add in AMIP driver (I would open a separate issue for this in CA for this. Test case to be used for initial integration test is [moist baroclinic wave](https://github.com/CliMA/ClimaAtmos.jl/blob/c28ea7a16a581c72a4fd7783f2744c011a04b46b/examples/hybrid/define_post_processing.jl#L323))
...

Details are subject to change as well as tasks/subtasks as things and plans are refined.

## Working branch
[`valeria/spherical-harmonics`](https://github.com/CliMA/ClimaCore.jl/tree/valeria/spherical-harmonics)

## Reviewers
@charleskawczynski and possibly other folks who have worked on/with the prior implementation (e.g., @LenkaNovak , @akshaysridhar )

**Comment by LenkaNovak** [comment]
Looks good! I would say the pure translation would take 1 week, so if we want to investigate other Julia packages, as well as the testing and documentation, I would allow more time (an additional week or so). Also, in the long term this should live wherever we do diagnostics on the regridded data ([ClimaDiagnostics.jl](https://github.com/CliMA/ClimaDiagnostics)?), but for the time being I agree that `ClimaCore/lib` seems most appropriate.

**Comment by LenkaNovak** [comment]
@jiahe23 and @akshaysridhar , you guys experimented with CM's `Spectra` code recently. Would you have any pointers/branches/tips/preferences?

**Comment by jiahe23** [comment]
I have a very outdated branch in [CA](https://github.com/CliMA/ClimaAtmos.jl/tree/jh/post-proc-util/examples/hybrid/sphere/post_processing_utilities) that I adopted the CM spectra calculation. It worked fine. I have generated KE spectra plots that looked reasonable by that time.

**Comment by valeriabarra** [comment]
Thanks for the pointers!

**Comment by valeriabarra** [comment]
Now that #979 is finally merged, I would propose opening a new SDI/issue for the enhanced interface and remaining enhancements (i.e., potential use of external packages). I prefer keep things organized and this was already a pretty long SDI/PR 

What do you think, @charleskawczynski ?

**Comment by valeriabarra** [comment]
I will mark this as complete and will open issues in the downstream repos (ClimaAtmos and ClimaCoupler) for the integration in them. 
I would also leave the 2 enhancement bullet points to a separate issue/SDI for the future revamping of the interface

**Comment by charleskawczynski** [comment]
> .... What do you think, @charleskawczynski ?

That sounds good. If using features in this package require many lines of code (e.g., more than 20) in an existing script, then I suggest we break off a subtask of trying to make a good wrapper around the remapping pipeline.
